### ISSUE TITLE
Resolve the CR-LF issue

### ISSUE THREAD

**Issue by mshahbaz** [NetASM/NetASM-python#2]
Doesn't work well with Windows. Need to change this in source files and setup scripts.

**Comment by feamster** [comment]
Just apply dos2unix to all of your files.

Then fix whatever editor you're using to end lines properly.

**Comment by mshahbaz** [comment]
All my editors are already set to unix style (LF). Not sure how these files ended up with CL-RF.

**Comment by mshahbaz** [comment]
Not an issue, so, closing it.
