### ISSUE TITLE
Error executing netasm.back_ends.soft_switch.datapath.launch

### ISSUE THREAD

**Issue by weirongj** [NetASM/NetASM-python#5]
I downloaded the NetASM-python VM and tried the standalone test.

$ sudopy python ~/pox/pox.py --no-openflow netasm.back_ends.soft_switch.datapath --policy="netasm.examples.netasm.standalone.hub" --standalone

Error executing netasm.back_ends.soft_switch.datapath.launch
TypeError: launch() got an unexpected keyword argument 'policy'

![image](https://cloud.githubusercontent.com/assets/3904748/8553621/8e935e3a-2499-11e5-8428-7fd16d4fb4f3.png)

**Comment by mshahbaz** [comment]
I will look into this and get back to you shortly. I also have to reply to your email too.

**Comment by mshahbaz** [comment]
I just tested this and it's working at my end. Can you check if the vagrant was setup properly?

**Comment by mshahbaz** [comment]
I'm marking this issue as closed.

**Comment by weirongj** [comment]
Ok. But just wonder why it could be affected by vagrant which runs on host, while NetASM runs within the VM. Thanks.

**Comment by mshahbaz** [comment]
In your case, it's saying that it wasn't able to find the --policy flag. However, if you look inside the code for datapath.py, the flag is defined in there. I don't know why are you getting this error. It's working fine at my end.

**Comment by weirongj** [comment]
Right, that puzzled me too..
